apiVersion: v1
kind: Secret
metadata:
  name: tfgapp-git
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Vkius/apptfg.git
  type: git
  insecure: "true"
  forceHttpBasicAuth: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: tfgapp-helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: oci://registry-1.docker.io/bitnamicharts/
  type: helm
 