cloneStaticSiteFromGit:
  enabled: true
  repository: "https://github.com/Vkius/website.git"
  branch: "main"
  enableAutoRefresh: false
  interval: 60
  resourcesPreset: "nano"
service:
  ## @param service.type Apache Service type
  ##
  type: NodePort
  ports:
    http: 8080
    https: 8443
readinessProbe:
  enabled: false

