cloneHtdocsFromGit:
  enabled: true
  repository: "https://github.com/Vkius/website.git"
  branch: "pruebas"
  enableAutoRefresh: true
  interval: 60
  resourcesPreset: "nano"
service:
  ## @param service.type Apache Service type
  ##
  type: NodePort
