cloneStaticSiteFromGit:
  enabled: true
  repository: "https://github.com/Vkius/website.git"
  branch: "main"
  enableAutoRefresh: false
  interval: 60
  resourcesPreset: "nano"
image:
  registry: docker.io
  repository: bitnami/nginx
  tag: 1.26.0-debian-12-r1
service:
  ## @param service.type Apache Service type
  ##
  type: NodePort
  ports:
    http: 8080
    https: 8443
readinessProbe:
  enabled: false

