kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: tfgapp-n1
  namespace: argocd
spec:
  project: tfgapp
  source:
    repoURL: https://github.com/Vkius/apptfg.git
    path: "."
    targetRevision: main
    ref: main_repository   
  sources:
    - repoURL: https://github.com/Vkius/apptfg.git
      targetRevision: main
      ref: main_repository
    - repoURL: https://charts.bitnami.com/bitnami
      chart: nginx
      targetRevision: 16.0.6
      helm:
        version: v3
        releaseName: nginx
        passCredentials: true
        valueFiles:
          - values.yaml
          - $main_repository/tfgapp-values.yml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tfgapp-v1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
  revisionHistoryLimit: 5